services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: geethapl/hello-world-app:latest
    container_name: java-app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    name: my-custom-network
    driver: bridge