apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: geetha  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: java-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "db"
            - name: REDIS_HOST
              value: "redis"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: geetha
spec:
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
