name: Docker Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Validate JAR
        run: java -jar target/hello-world-1.0-SNAPSHOT.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-jar
          path: target/*.jar
          
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: maven-jar
          path: target

      - name: Build Docker Image
        run: docker build -f docker/Dockerfile -t hello-world-app .

      - name: Push Docker Image
        run: docker push geethapl/hello-world-app:latest


