name: CI-CD Pipeline (ECR + EKS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG: v${{ github.run_number }}

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.push-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Validate JAR
        run: java -jar target/hello-world-1.0-SNAPSHOT.jar

      - name: Set version
        run: echo "TAG=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker Image via Compose
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Image for ECR
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker tag geethapl/hello-world-app:latest $ECR_REGISTRY/gee-ecr:${{ env.TAG }}

      - name: Push Image to ECR
        id: push-image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI=$ECR_REGISTRY/gee-ecr:${{ env.TAG }}
          docker push $IMAGE_URI
          echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name demo-eks-cluster1

      - name: Create Namespace
        run: |
          kubectl create namespace geetha || true

      - name: Update Image in Manifest
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ needs.build.outputs.image }}|g" docker/manifest.yml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f docker/manifest.yml -n geetha

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/hello-world-app -n geetha
